### ISSUE TITLE
E_WARNING Undefined variable $language

### ISSUE THREAD

**Issue by bynect** [amnemonic/dokuprism#3]
I'm getting many warnings, is this normal? I'm on php 8
```
E_WARNING: Undefined variable $language
/var/www/dokuwiki/lib/plugins/dokuprism/syntax/code.php(64)
    #0 /var/www/dokuwiki/lib/plugins/dokuprism/syntax/code.php(64): dokuwiki\ErrorHandler::errorHandler()
    #1 /var/www/dokuwiki/inc/parser/renderer.php(119): syntax_plugin_dokuprism_code->render()
    #2 /var/www/dokuwiki/inc/parserutils.php(700): Doku_Renderer->plugin()
    #3 /var/www/dokuwiki/inc/parserutils.php(158): p_render()
    #4 /var/www/dokuwiki/inc/parserutils.php(96): p_cached_output()
    #5 /var/www/dokuwiki/inc/Ui/PageView.php(68): p_wiki_xhtml()
    #6 /var/www/dokuwiki/inc/Action/Show.php(37): dokuwiki\Ui\PageView->show()
    #7 /var/www/dokuwiki/inc/template.php(100): dokuwiki\Action\Show->tplContent()
    #8 [internal function]: tpl_content_core()
    #9 /var/www/dokuwiki/inc/Extension/Event.php(133): call_user_func_array()
    #10 /var/www/dokuwiki/inc/Extension/Event.php(199): dokuwiki\Extension\Event->trigger()
    #11 /var/www/dokuwiki/inc/template.php(85): dokuwiki\Extension\Event::createAndTrigger()
    #12 /var/www/dokuwiki/lib/tpl/dokuwiki/main.php(59): tpl_content()
    #13 /var/www/dokuwiki/inc/actions.php(27): include('...')
    #14 /var/www/dokuwiki/doku.php(126): act_dispatch()
    #15 {main}
```

**Comment by amnemonic** [comment]
Can you provide exact version of your DokuWiki? It should be visible in your admin panel.

**Comment by bynect** [comment]
Release 2023-04-04a "Jack Jackrum"

**Comment by amnemonic** [comment]
Thank you for reporting bug, it should be fixed in current release. If you don't see option to update plugin please try to force 
`Re-install` it in extensions manager. I would be glad if you let me know if issue is fixed.

![obraz](https://github.com/amnemonic/dokuprism/assets/29899901/e3bde757-f03d-48e8-9eb0-c76a4a5d9eb2)

**Comment by bynect** [comment]
Now it works! Thankyou
